version: "3.6"
#IMPORTANTE: Você terá 1.5 CPUs e 3.0GB
services:
  api1:
    image: quay.io/will/quarkus-app
    environment:
      DB_HOST: db
      QUARKUS_LOG_CONSOLE_ENABLE: 'false'
      QUARKUS_LOG_FILE_ENABLE: 'false'
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 50
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.6GB'
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  api2:
    image: quay.io/will/quarkus-app
    environment:
      DB_HOST: db
      QUARKUS_LOG_CONSOLE_ENABLE: 'false'
      QUARKUS_LOG_FILE_ENABLE: 'false'
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 50
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.6GB'
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  nginx:
    image: nginx:1.25.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'

  db:
    image: postgres:15.4
    command: postgres -c 'max_connections=200' -c 'shared_buffers=512MB' -c 'effective_io_concurrency=200' -c 'fsync=off' -c 'effective_cache_size=1200MB' -c 'synchronous_commit=off' -c 'min_wal_size=1GB' -c 'max_wal_size=4GB' -c 'full_page_writes=false'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkus
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '1.6GB'
    healthcheck:
      test: [ "CMD-SHELL", "[ -r /var/run/postgresql/ready ] || ( pg_isready && touch /var/run/postgresql/ready)" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s